### ISSUE TITLE
Fatal error: Class 'Phois\Whois\Whois' not found

### ISSUE THREAD

**Issue by mintux** [regru/php-whois#56]
i clone it here:
/home/mrg/www/Test/php-whois
![image](https://cloud.githubusercontent.com/assets/3824913/14022245/9c1ca166-f1fc-11e5-9846-422296ec2139.png)
then run:
http://localhost/Test/php-whois/examples/usage-example.php
 And get this error:

>  Fatal error: Class 'Phois\Whois\Whois' not found in /home/mrg/www/Test/php-whois/examples/usage-example.php on line 8

My os is linux mint 17.3 64bit
PHP Version 5.5.9-1ubuntu4.14
Aapache 2.4

**Comment by bjdeliduka** [comment]
edit usage-example.php adding

include '../src/Phois/Whois/Whois.php';
